accounts/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('rest-auth/',include("rest_auth.urls")),
]

accounts/urls.py
from django.urls import path, include
from .views import HomePageTemplateView, SignUpView
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth import views

urlpatterns = [

    path("home/", HomePageTemplateView.as_view(), name="home"),

    path("sign-up/", SignUpView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),


]

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('', views.PropertyHomeView.as_view(), name="home"),
    path('property-list/', views.PropertyListView.as_view(), name="list"),
    path('property-detail/<int:pk>/', views.PropertyDetailView.as_view(), name="detail"),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('property/', include("property.urls", namespace='property')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

accounts/api/models.py
from django.db import models

# Create your models here.

accounts/models.py
from django.db import models

# Create your models here.

property/models.py
from django.db import models
from utils.file_utils import generae_filename
# Create your models here.
from ckeditor_uploader.fields import RichTextUploadingField

def upload_path(instance, file_name):

    return generae_filename(file_name)

class Property(models.Model):

    street = models.CharField(max_length=255)

    city = models.CharField(max_length=255)
    
    state = models.CharField(max_length=255)
    
    zip_code = models.CharField(max_length=255)
    
    price = models.IntegerField()
    
    bedrooms = models.IntegerField()
    
    bathrooms = models.IntegerField()
    
    garage = models.IntegerField()
    
    square_feet = models.IntegerField()
    
    lot_size = models.DecimalField(decimal_places=2, max_digits=3)
    
    created_at = models.DateTimeField(auto_now_add=True)

    hero_image = models.ImageField(upload_to=upload_path)

    slide_img_1 = models.ImageField(upload_to=upload_path)

    slide_img_2 = models.ImageField(upload_to=upload_path)
    
    slide_img_3 = models.ImageField(upload_to=upload_path)
    
    slide_img_4 = models.ImageField(upload_to=upload_path)
    
    slide_img_5 = models.ImageField(upload_to=upload_path)
    
    slide_img_6 = models.ImageField(upload_to=upload_path)

    description = RichTextUploadingField()

    class Meta:

        verbose_name_plural="Properties"
    
    def __str__(self):

        return self.street

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class SignUpForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:

        model = User

        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):

        email = self.cleaned_data.get('email')

        users = User.objects.all()

        for user in users:

            if user.email == email:

                raise forms.ValidationError("email already taken.")

        return email

    def save(self, commit=True):
        
        user = super().save(commit=False)

        user.is_staff = True

        if commit:

            user.save()

        return user

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from . import forms
from django.contrib.auth.models import User
from django.forms import ValidationError
from django.http import HttpResponseRedirect
# Create your views here.

class HomePageTemplateView(TemplateView):

    template_name = "accounts/home.html"

class SignUpView(CreateView):

    template_name = 'registration/signup.html'

    form_class = forms.SignUpForm

    success_url = reverse_lazy("login")

property/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, DetailView)
from .models import Property

# Create your views here.


def index(request):

    return render(request, 'property/home.html')


class PropertyHomeView(TemplateView):

    template_name = 'property/home.html'

    def get_queryset(self):

        queryset = Property.objects.all()

        return queryset

    def get_context_data(self):

        context_data = super().get_context_data()

        context_data['object_list'] = self.get_queryset().order_by(
            '-created_at')[:3]

        return context_data

class PropertyListView(ListView):

    model = Property

class PropertyDetailView(DetailView):

    model = Property

accounts/templates/accounts/home.html
{% extends 'base.html' %}


{% block content %}
    Welcome from home page
{% endblock content %}
    

property/templates/property/home.html
{% extends 'base.html' %}


{% block content %}
<section id="showcase">
    <div class="container text-center">
        <div class="home-search p-5">
            <div class="overlay p-5">
                <h1 class="display-4 mb-4">
                    Property Searching Just Got So Easy
                </h1>
                <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae quas, asperiores
                    eveniet vel nostrum magnam
                    voluptatum tempore! Consectetur, id commodi!</p>
                <div class="search">
                    <form action="search.html">
                        <!-- Form Row 1 -->
                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label class="sr-only">Keywords</label>
                                <input type="text" name="keywords" class="form-control"
                                    placeholder="Keyword (Pool, Garage, etc)">
                            </div>

                            <div class="col-md-4 mb-3">
                                <label class="sr-only">City</label>
                                <input type="text" name="city" class="form-control" placeholder="City">
                            </div>

                            <div class="col-md-4 mb-3">
                                <label class="sr-only">State</label>
                                <select name="state" class="form-control">
                                    <option selected="true" disabled="disabled">State (All)</option>
                                    <option value="AL">Alabama</option>
                                    <option value="AK">Alaska</option>
                                    <option value="AZ">Arizona</option>
                                    <option value="AR">Arkansas</option>
                                    <option value="CA">California</option>
                                    <option value="CO">Colorado</option>
                                    <option value="CT">Connecticut</option>
                                    <option value="DE">Delaware</option>
                                    <option value="DC">District Of Columbia</option>
                                    <option value="FL">Florida</option>
                                    <option value="GA">Georgia</option>
                                    <option value="HI">Hawaii</option>
                                    <option value="ID">Idaho</option>
                                    <option value="IL">Illinois</option>
                                    <option value="IN">Indiana</option>
                                    <option value="IA">Iowa</option>
                                    <option value="KS">Kansas</option>
                                    <option value="KY">Kentucky</option>
                                    <option value="LA">Louisiana</option>
                                    <option value="ME">Maine</option>
                                    <option value="MD">Maryland</option>
                                    <option value="MA">Massachusetts</option>
                                    <option value="MI">Michigan</option>
                                    <option value="MN">Minnesota</option>
                                    <option value="MS">Mississippi</option>
                                    <option value="MO">Missouri</option>
                                    <option value="MT">Montana</option>
                                    <option value="NE">Nebraska</option>
                                    <option value="NV">Nevada</option>
                                    <option value="NH">New Hampshire</option>
                                    <option value="NJ">New Jersey</option>
                                    <option value="NM">New Mexico</option>
                                    <option value="NY">New York</option>
                                    <option value="NC">North Carolina</option>
                                    <option value="ND">North Dakota</option>
                                    <option value="OH">Ohio</option>
                                    <option value="OK">Oklahoma</option>
                                    <option value="OR">Oregon</option>
                                    <option value="PA">Pennsylvania</option>
                                    <option value="RI">Rhode Island</option>
                                    <option value="SC">South Carolina</option>
                                    <option value="SD">South Dakota</option>
                                    <option value="TN">Tennessee</option>
                                    <option value="TX">Texas</option>
                                    <option value="UT">Utah</option>
                                    <option value="VT">Vermont</option>
                                    <option value="VA">Virginia</option>
                                    <option value="WA">Washington</option>
                                    <option value="WV">West Virginia</option>
                                    <option value="WI">Wisconsin</option>
                                    <option value="WY">Wyoming</option>
                                </select>
                            </div>
                        </div>
                        <!-- Form Row 2 -->
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label class="sr-only">Bedrooms</label>
                                <select name="bedrooms" class="form-control">
                                    <option selected="true" disabled="disabled">Bedrooms (All)</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <select name="price" class="form-control" id="type">
                                    <option selected="true" disabled="disabled">Max Price (Any)</option>
                                    <option value="100000">$100,000</option>
                                    <option value="200000">$200,000</option>
                                    <option value="300000">$300,000</option>
                                    <option value="400000">$400,000</option>
                                    <option value="500000">$500,000</option>
                                    <option value="600000">$600,000</option>
                                    <option value="700000">$700,000</option>
                                    <option value="800000">$800,000</option>
                                    <option value="900000">$900,000</option>
                                    <option value="1000000">$1M+</option>
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
    <div class="container">
        <h3 class="text-center mb-3">Latest Listings</h3>
        <div class="row">
            {% for property in object_list %}
                <div class="col-md-6 col-lg-4 mb-4">
                    {% include 'property/snippets/property_card.html' with property=property %}
                </div>
            {% endfor %}
        </div>
    </div>
</section>




<section id="services" class="py-5 bg-secondary text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-4">
                <i class="fas fa-comment fa-4x mr-4"></i>
                <hr>
                <h3>Consulting Services</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae,
                    provident iste consequatur
                    hic dignissimos ratione ea quae.</p>
            </div>
            <div class="col-md-4">
                <i class="fas fa-home fa-4x mr-4"></i>
                <hr>
                <h3>Propery Management</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae,
                    provident iste consequatur
                    hic dignissimos ratione ea quae.</p>
            </div>
            <div class="col-md-4">
                <i class="fas fa-suitcase fa-4x mr-4"></i>
                <hr>
                <h3>Renting & Selling</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae,
                    provident iste consequatur
                    hic dignissimos ratione ea quae.</p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

property/templates/property/property_detail.html
{% extends 'base.html' %}

{% load static %}


{% block css %}
<link href="{% static 'assets/css/lightbox.min.css' %}" rel="stylesheet">
{% endblock css %}


{% block content %}


<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">{{ property.street }}</h1>
                <p class="lead">
                    <i class="fas fa-map-marker"></i> {{ property.city}} {{ property.state }},
                    {{ property.zip }}</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Listing -->
    <section id="listing" class="py-4">
        <div class="container">
            {% include 'property/snippets/breadcumb.html' with path=request.path street=property.street %}
            <a href="{% url 'property:list' %}" class="btn btn-light mb-4">Back To Listings</a>
            <div class="row">
                <div class="col-md-9">
                    <!-- Home Main Image -->
                    <img src="{{ object.hero_image.url }}" alt="" class="img-main img-fluid mb-3">
                    <!-- Thumbnails -->
                <div class="row mb-5 thumbs">
                    <div class="col-md-2">
                        <a href="{{ object.slide_img_1.url }}" data-lightbox="home-images">
                            <img src="{{ object.slide_img_1.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    <div class="col-md-2">
                        <a href="{{ object.slide_img_2.url }}" data-lightbox="home-images">
                            <img src="{{ object.slide_img_2.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    <div class="col-md-2">
                        <a href="{{ object.slide_img_3.url }}" data-lightbox="home-images">
                            <img src="{{ object.slide_img_3.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    <div class="col-md-2">
                        <a href="{{ object.slide_img_4.url }}" data-lightbox="home-images">
                            <img src="{{ object.slide_img_4.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    <div class="col-md-2">
                        <a href="{{ object.slide_img_5.url }}" data-lightbox="home-images">
                            <img src="{{ object.slide_img_5.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    <div class="col-md-2">
                        <a href="{{ object.slide_img_6.url }}" data-lightbox="home-images">
                            <img src="{{ object.slide_img_6.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                </div>
                <!-- Fields -->
                <div class="row mb-5 fields">
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-money-bill-alt"></i> Asking Price:
                                <span class="float-right">${{ object.price }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-bed"></i> Bedrooms:
                                <span class="float-right">{{ object.bedrooms }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-bath"></i> Bathrooms:
                                <span class="float-right">{{ object.bathrooms }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-car"></i> Garage:
                                <span class="float-right">{{ object.garage }}
                                </span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-th-large"></i> Square Feet:
                                <span class="float-right">{{ object.square_feet }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-square"></i> Lot Size:
                                <span class="float-right">{{ object.lot_size }} Acres
                                </span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-calendar"></i> Listing Date:
                                <span class="float-right">8/30/2018</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-bed"></i> Realtor:
                                <span class="float-right">Kyle Brown
                                </span>
                            </li>


                        </ul>
                    </div>
                </div>

                <!-- Description -->
                <div class="row mb-5">
                    <div class="col-md-12">
                        {{ property.description|safe }}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card mb-3">
                    <img class="card-img-top" src="assets/img/realtors/kyle.jpg" alt="Seller of the month">
                    <div class="card-body">
                        <h5 class="card-title">Property Realtor</h5>
                        <h6 class="text-secondary">Kyle Brown</h6>
                    </div>
                </div>
                <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An
                    Inquiry</button>
            </div>
        </div>
    </div>
</section>

<!-- Inquiry Modal -->
<div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="property_name" class="col-form-label">Property:</label>
                        <input type="text" name="listing" class="form-control" value="45 Drivewood Cirlce" disabled>
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" name="name" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-form-label">Email:</label>
                        <input type="email" name="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="phone" class="col-form-label">Phone:</label>
                        <input type="text" name="phone" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="message" class="col-form-label">Message:</label>
                        <textarea name="message" class="form-control"></textarea>
                    </div>
                    <hr>
                    <input type="submit" value="Send" class="btn btn-block btn-secondary">
                </form>
            </div>
        </div>
    </div>
</div>


{% block javascript %}
<script src="{% static 'assets/js/lightbox.min.js' %}"></script>
{% endblock javascript  %}


{% endblock content %}

property/templates/property/property_list.html
{% extends 'base.html' %}


{% block content %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">Browse Our Properties</h1>
                <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
            </div>
        </div>
    </div>
</section>

{% include 'property/snippets/breadcumb.html' with path=request.path %}

<!-- Listings -->
<section id="listings" class="py-4">
    <div class="container">
        <h3 class="text-center mb-3">Latest Listings</h3>
        <div class="row">
            {% for property in object_list %}
            <div class="col-md-6 col-lg-4 mb-4">
                {% include 'property/snippets/property_card.html' with property=property %}
            </div>
            {% endfor %}
        </div>
    </div>
</section>


{% endblock content %}

property/templates/property/snippets/breadcumb.html
<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'property:home' %}">Home</a>
                </li>

                {% if 'list' in path %}
                <li class="breadcrumb-item active"> Browse Listings</li>
                {% else %}

                <li class="breadcrumb-item">
                    <a href="{% url 'property:list' %}">Listings</a>
                </li>
                <li class="breadcrumb-item active">{{ street }}</li>
                {% endif %}

            </ol>
        </nav>
    </div>
</section>

property/templates/property/snippets/footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> BT Real Estate
</footer>

property/templates/property/snippets/header.html
<section id="top-bar" class="p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fas fa-phone"></i> (617)-555-5555
            </div>
            <div class="col-md-4">
                <i class="fas fa-envelope-open"></i> arkarhtethan@gmail.co
            </div>
            <div class="col-md-4">
                <div class="social text-right">
                    <a href="#">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-pinterest"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

property/templates/property/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'property:home' %}">
            <img src="{% static 'assets/img/logo.png' %}" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'property:home' %}">Home</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="nav-link" href="about.html">About</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'property:list' %}">Featured Listings</a>
                </li>
            </ul>


            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown" style="text-transform: initial">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        <span>
                            Welcome {{ request.user}}
                        </span>
                    </a>
                    <div class="dropdown-menu">
                        <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
                        <a href="{% url 'password_change' %}" class="dropdown-item">Change Password</a>
                        <a href="{% url 'password_reset' %}" class="dropdown-item">Reset Password</a>
                    </div>
                </li>


                {% else %}
                <li class="nav-item lowercase mr-3">
                    <a class="nav-link" href="{% url 'register' %}">
                        <i class="fas fa-user-plus"></i> Register</a>
                </li>
                <li class="nav-item mr-3">
                    <a href="{% url 'login' %}" class="nav-link">
                        <i class="fas fa-sign-in-alt"></i>

                        Login</a>
                </li>

                {% endif %}

            </ul>

        </div>
    </div>
</nav>

property/templates/property/snippets/property_card.html
<div class="card listing-preview">
    <img class="card-img-top" src="{{ property.hero_image.url }}" alt="">
    <div class="card-img-overlay">
        <h2>
            <span class="badge badge-secondary text-white">${{ property.price }}</span>
        </h2>
    </div>
    <div class="card-body">
        <div class="listing-heading text-center">
            <h4 class="text-primary">{{ property.street }}</h4>
            <p>
                <i class="fas fa-map-marker text-secondary"></i> {{ property.city}} {{ property.state }},
                {{ property.zip }}</p>
        </div>
        <hr>
        <div class="row py-2 text-secondary">
            <div class="col-6">
                <i class="fas fa-th-large"></i> Sqft: {{ property.square_feet}}</div>
            <div class="col-6">
                <i class="fas fa-car"></i> Garage: {{ property.garage }}</div>
        </div>
        <div class="row py-2 text-secondary">
            <div class="col-6">
                <i class="fas fa-bed"></i> Bedrooms: {{ property.bedrooms }}</div>
            <div class="col-6">
                <i class="fas fa-bath"></i> Bathrooms: {{ property.bathrooms }}</div>
        </div>
        <hr>
        <div class="row py-2 text-secondary">
            <div class="col-12">
                <i class="fas fa-user"></i> Kyle Brown</div>
        </div>
        <div class="row text-secondary pb-2">
            <div class="col-12">
                <i class="fas fa-clock"></i> {{ property.created_at|timesince}} ago</div>
        </div>
        <hr>
        <a href="{% url 'property:detail' pk=property.pk %}" class="btn btn-primary btn-block">More Info</a>
    </div>
</div>